[package]
name = "wasmi_dart"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.72.*"

[dependencies]
flutter_rust_bridge = "1.72.*"
wasmi = "0.29.0"
wasmi_wasi = "0.29.0"
wasi-common = "7.0.0" # the latest is 7.0.0, but it's not compatible with wasmi_wasi
cap-std = "0.26.0"
wat = "1.0.61"
anyhow = "1.0.0"
once_cell = "1.0.0"
# wasmtime-wasi = { version = "7.0.0", optional = true }
# wasmtime-types = { version = "7.0.0", optional = true }
wasmtime = { version = "7.0.0", optional = true }

[features]
wasmtime = ["dep:wasmtime"]
# wasi = ["dep:wasmi_wasi", "dep:wasmtime-wasi"]