name: wasm_run
description: Web Assembly executor. Uses Rust's wasmtime optimizing runtime or wasmi interpreter.
version: 0.0.1+1
homepage: https://github.com/juancastillo0/wasm_run

topics:
  - wasm
  - interop
  - runtime
  - interpreter
  - ffi

environment:
  sdk: ">=3.1.0 <4.0.0"

flutter:
  assets:
    - lib/assets/

dependencies:
  meta: ^1.8.0
  ffi: ^2.1.0
  flutter_rust_bridge: ^1.82.1
  freezed_annotation: ^2.2.0
  wasm_interop: ^2.0.1
  logging: ^1.1.0
  collection: ^1.17.0
  http: ^0.13.5

dev_dependencies:
  ffigen: ^9.0.1
  test: ^1.21.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  very_good_analysis: ^5.0.0
