[package]
name = "wasm_run_dart"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.4"

[dependencies]
flutter_rust_bridge = "1.82.4"
anyhow = "1.0.75"
once_cell = "1.18.0"
wat = "1.0.77"

rayon = "1.8.0"

wasi-common = "14.0.4"
cap-std = "2.0.0"
wasmtime = "15.0.1"
wasmtime-wasi = "14.0.4"

[features]
default = ["wasmtime", "wasi"]
wasi = []
wasmi = []
wasmtime = []
