[package]
name = "wasm_run_dart"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.*"

[dependencies]
flutter_rust_bridge = "1.82.*"
anyhow = "1.0.0"
once_cell = "1.0.0"
wat = "1.0.61"

wasmi = "0.30.0"
wasi-common = { version = "2.0.0", optional = true } # the latest is 7.0.0, but it's not compatible with wasmi_wasi
cap-std = { version = "0.26.0", optional = true }
wasmi_wasi = { version = "0.30.0", optional = true }

[features]
default = ["wasmi", "wasi"]
wasi = ["dep:wasmi_wasi", "dep:wasi-common", "dep:cap-std"]
wasmi = []
wasmtime = []
